### ISSUE TITLE
Show if place is open

### ISSUE THREAD

**Issue by oed** [cthit/mat#12]
Each food place should have an indication if it's open at the current time. Bonus points if the open places are shown first and have a green color, while the closed places have a red color.

**Comment by lindskogen** [comment]
Fantastic idea! A problem I can see is for days like today, "kristi himmelsfärdsdagen" would be hard to catch.

**Comment by oed** [comment]
Isn't there some kind of api to get holidays?

**Comment by oed** [comment]
Isn't there some kind of api to get holidays?

**Comment by Edholm** [comment]
Even though there is an holiday today, it doesn't mean that that particular restaurant is closed.

**Comment by lindskogen** [comment]
That's not the hard part. Places have different opening times at different holidays.

**Comment by oed** [comment]
There could be a warning when the time is potentially wrong

**Comment by MrLinker** [comment]
Maybe [Google's Places API](https://developers.google.com/places/web-service/details#PlaceDetailsResults) is what should be used?
