### ISSUE TITLE
Add link to respective homepage

### ISSUE THREAD

**Issue by Edholm** [cthit/mat#13]
Clicking on the name could for example open the restaurant's homepage.

**Comment by Portals** [comment]
Do people still think this is important after the rewrite? Adding another blue link feels like it can be too much.

![image](https://user-images.githubusercontent.com/7045380/40649765-00f3fdac-6332-11e8-9530-72a99d80e4a4.png)

![image](https://user-images.githubusercontent.com/7045380/40649868-2c529670-6332-11e8-8b38-8cb15dd3e4bc.png)
