### ISSUE TITLE
Add SSL/TLS to mat.chalmers.it

### ISSUE THREAD

**Issue by hsson** [cthit/mat#25]
Chrome starts marking non-https sites as "Not Secure" in July [(source)](https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html).

**Comment by hulthe** [comment]
[mat.chalmers.it](https://mat.chalmers.it) was already being served over HTTPS but was missing a redirect from HTTP. This has now been resolved:
```
$ curl http://mat.chalmers.it
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>302 Found</title>
> </head><body>
> <h1>Found</h1>
> <p>The document has moved <a href="https://mat.chalmers.it/">here</a>.</p>
> </body></html>
```
