### ISSUE TITLE
Warn user that the opening hours might be incorrect if it's a holiday.

### ISSUE THREAD

**Issue by Portals** [cthit/mat#37]
Maybe use this api? 

https://api.dryg.net

**Comment by Portals** [comment]
Not according to the places api: https://developers.google.com/places/web-service/details

**Comment by Dr-Horv** [comment]
"opening_hours contains the following information: ..." on hte page you linked?

**Comment by Dr-Horv** [comment]
Ah, I thought you were speaking about opening hours, not holidays. Wrote to fast, my apologies

**Comment by Portals** [comment]
Closing since this was due to the old version of mat.
