### ISSUE TITLE
Display distance to restaurant

### ISSUE THREAD

**Issue by cajoho99** [cthit/mat#47]
Add an option to display and sort resturaunts by distance from the user/hubben. Maybe by using the google maps API or OpenStreetMap?

**Comment by Portals** [comment]
Awesome idea! Shouldn't be so hard since we already are retrieving information from Google Places! A sort function is something I have thought of before, but only if something is open or closed, distance is a great idea! ❤️

**Comment by Portals** [comment]
Closing since this was due to the old version of mat.
